### ISSUE TITLE
Update 2019 logos to new "dateless" logo on coolestprojects.org

### ISSUE THREAD

**Issue by danielmerriman** [RaspberryPiFoundation/coolestprojects.org#21]
On `coolestprojects.org` there are logos that say `2019` on them, which obviously are out of date. I can see them in the following locations. These need to be updated to the "dateless" logo (available [here](https://drive.google.com/drive/folders/1xhKN9-7o5OXmfjnk7dzh4mEt7ZwYsV2U))

Footer [on Homepage:](https://coolestprojects.org)

<img width="1274" alt="Screenshot 2020-01-30 at 09 22 31" src="https://user-images.githubusercontent.com/46445857/73436268-1a844500-4342-11ea-9f02-041ca4d645c5.png">

Header [here:](https://coolestprojects.org/events)

<img width="1274" alt="Screenshot 2020-01-30 at 09 24 04" src="https://user-images.githubusercontent.com/46445857/73436375-51f2f180-4342-11ea-8fcf-32d82829b71a.png">

Header [here:](https://coolestprojects.org/showcase)

<img width="1274" alt="Screenshot 2020-01-30 at 09 25 19" src="https://user-images.githubusercontent.com/46445857/73436457-751da100-4342-11ea-8b1c-b94459f52074.png">

Header [on Sponsors page:](https://coolestprojects.org/sponsors/)

<img width="1274" alt="Screenshot 2020-01-30 at 09 26 13" src="https://user-images.githubusercontent.com/46445857/73436521-941c3300-4342-11ea-87ac-f7caf2119896.png">

Header [on News page:](https://coolestprojects.org/news/)

<img width="1274" alt="Screenshot 2020-01-30 at 09 27 18" src="https://user-images.githubusercontent.com/46445857/73436597-bada6980-4342-11ea-964d-f65f82fc4759.png">

Header [on Bursaries page:](https://coolestprojects.org/bursaries/)

<img width="1274" alt="Screenshot 2020-01-30 at 09 28 06" src="https://user-images.githubusercontent.com/46445857/73436838-245a7800-4343-11ea-8c7f-940d3fc7bcee.png">

Header [on Rules page:](https://coolestprojects.org/rules-and-regulations/)

<img width="1274" alt="Screenshot 2020-01-30 at 09 34 16" src="https://user-images.githubusercontent.com/46445857/73437133-b4002680-4343-11ea-8f97-e78c39d72865.png">

**Comment by ArayB** [comment]
@danielmerriman Do we have an undated version of the logo on white background as used in the footer?

I can't find one in google drive.

**Comment by ArayB** [comment]
Images have been updated now
