### ISSUE TITLE
Add 3 new locations to coolestprojects.org

### ISSUE THREAD

**Issue by danielmerriman** [RaspberryPiFoundation/coolestprojects.org#22]
**Issue:**

Coolest Projects have a commitment to some of the Coolest Projects regions to promote their events. In the short term, the three main regions we're concerned about are Romania, Malaysia, and Belgium.

We do not need to process submissions to their events or handle any of the administration, we just need to link to their sites from coolestprojects.org.

Belgium: https://coolestprojects.be
Malaysia: https://www.pscpen.com/events/coolestprojects2019
Romania: http://www.coderdojo.ro/coolestprojects

It is possible that, in the future, further regions will need adding. However, the above 3 regions should be added in good time for the 2020 events (which commence in March).

**Possible Approach:**

Add the required countries to https://coolestprojects.org/events/

**Comment by LouiseRPF** [comment]
![image](https://user-images.githubusercontent.com/55977736/74849250-65392180-5330-11ea-967d-09c4984aa261.png)
This is what I'm thinking for this and I have shown this to Rosa. Let me know when this is being worked on and I can provide the images.
